# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'iddc-oc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iddc-oc
  pod 'iddc-xcode14.0', '2.7.398'

  target 'iddc-ocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iddc-ocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
